DROP TABLE IF EXISTS contract;


CREATE TABLE contract
(
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  par_id        INTEGER DEFAULT 0   NOT NULL,
  pay_id        INTEGER DEFAULT 0   NOT NULL,
  dog_id        INTEGER             NOT NULL,
  dog_num_s     VARCHAR             NOT NULL,
  dog_num       INTEGER             NOT NULL,
  name          VARCHAR             NOT NULL,
  reg_date      TIMESTAMP           NOT NULL,
  dog_type      INTEGER DEFAULT 0   NOT NULL,
  id_group      INTEGER DEFAULT 0   NOT NULL,
  id_department INTEGER DEFAULT 401 NOT NULL
);